export const experiences = [
  {
    id: "1",
    type: "job",
    company: "OpenAI",
    title: "Frontend Developer",
    start: "2023-01",
    end: "2024-05",
    description: "Worked on building accessible, fast React interfaces.",
    tags: ["React", "Next.js", "Internship"],
    image: "/screenshots/openai-ui.png",
  },
  {
    id: "2",
    type: "project",
    company: "Personal Project",
    title: "Game Portal",
    start: "2022-03",
    end: "2022-11",
    description: "Created a web-based game launcher and library in Unity.",
    tags: ["Unity", "C#", "GameDev"],
    image: "/screenshots/game-portal.png",
  },
  {
    id: "3",
    type: "job",
    company: "Freelance",
    title: "React Consultant",
    start: "2021-06",
    end: "2022-02",
    description: "Built component libraries and mentored junior developers.",
    tags: ["React", "Freelance"],
    image: "/screenshots/consultant.png",
  },
];
